@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion
title Chronos Seal V2.2 - Asset Encryption Tool

cd /d "%~dp0"

set "SCAN_FILE=_cs_scan.txt"
set "RESULT_FILE=_cs_result.txt"
set "VERIFY_FILE=_cs_verify.txt"
set "ORIGINALS_FILE=_cs_originals.txt"

:: ============================================================
:: STEP 0 - Welcome
:: ============================================================
cls
echo ============================================================
echo   Chronos Seal V2.2 - Asset Encryption Tool
echo ============================================================
echo.
echo   This tool MUST be run inside the RELEASE PACKAGE folder.
echo.
echo   Required files in current directory:
echo     - encrypt_config.json      ^(generated by GitHub Actions^)
echo     - decryptor.node           ^(compiled native module^)
echo     - encrypt_assets.js        ^(this tool^)
echo     - www\                     ^(deployed game directory^)
echo.
echo   Make sure you have a backup of your source project.
echo   Encryption is irreversible.
echo.
echo   Press any key to continue . . .
pause >nul

:: ============================================================
:: STEP 1 - Node.js environment check
:: ============================================================
echo.
echo [Step 1/7] Checking Node.js environment . . .
echo.

where node >nul 2>nul
if %errorlevel% neq 0 (
    echo   [ERROR] Node.js not found on this system.
    echo.
    echo   Please install Node.js 14 or later before running this tool.
    echo   See documentation for installation instructions.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)

for /f "delims=" %%v in ('node -v 2^>nul') do set "NODE_VER=%%v"

echo   [OK] Found Node.js !NODE_VER!
echo   [OK] Node.js environment ready.
echo.
echo   Press any key to scan asset files . . .
pause >nul

:: ============================================================
:: STEP 2 - Pre-flight check
:: ============================================================
echo.
echo [Step 2/7] Checking required files . . .
echo.

if not exist "encrypt_config.json" (
    echo   [ERROR] encrypt_config.json not found.
    echo           This file is generated by GitHub Actions.
    echo           See documentation for details.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)
echo   [OK] encrypt_config.json found.

if not exist "decryptor.node" (
    echo   [ERROR] decryptor.node not found in current directory.
    echo           This file is generated by GitHub Actions.
    echo           Without it, verification will fail.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)
echo   [OK] decryptor.node found.

if not exist "encrypt_assets.js" (
    echo   [ERROR] encrypt_assets.js not found.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)
echo   [OK] encrypt_assets.js found.

if not exist "www\" (
    echo   [ERROR] www\ directory not found.
    echo           This tool must be run inside the release package.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)
echo   [OK] www\ directory found.

echo.
echo   Press any key to scan asset files . . .
pause >nul

:: ============================================================
:: STEP 3 - Scan
:: ============================================================
echo.
echo [Step 3/7] Scanning asset files . . .
echo.

if exist "%SCAN_FILE%" del /q "%SCAN_FILE%" 2>nul

node "encrypt_assets.js" --scan
if %errorlevel% neq 0 (
    echo.
    echo   [ERROR] Scan failed. See messages above.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)

if not exist "%SCAN_FILE%" (
    echo.
    echo   [ERROR] Scan did not produce a result file.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)

set "TOTAL_FILES=0"
set /p TOTAL_FILES=<"%SCAN_FILE%"

if "%TOTAL_FILES%"=="0" (
    echo.
    echo   [INFO] No asset files found. Nothing to encrypt.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 0
)

echo.
echo   [OK] Found %TOTAL_FILES% asset file^(s^) to encrypt.
echo.
echo   Press any key to start encryption . . .
pause >nul

:: ============================================================
:: STEP 4 - Encrypt
:: ============================================================
echo.
echo [Step 4/7] Encrypting assets . . .
echo.

if exist "%RESULT_FILE%"    del /q "%RESULT_FILE%"    2>nul
if exist "%ORIGINALS_FILE%" del /q "%ORIGINALS_FILE%" 2>nul

node "encrypt_assets.js" --encrypt
if %errorlevel% neq 0 (
    echo.
    echo   [ERROR] Encryption aborted. See messages above.
    echo           DO NOT proceed. Restore your backup if needed.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)

if not exist "%RESULT_FILE%" (
    echo.
    echo   [ERROR] Encryption did not produce a result file.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)

set "SUCCESS_COUNT=0"
set "FAIL_COUNT=0"

for /f "tokens=1,2 delims=," %%a in ('type "%RESULT_FILE%"') do (
    set "SUCCESS_COUNT=%%a"
    set "FAIL_COUNT=%%b"
)

if not "%FAIL_COUNT%"=="0" (
    echo.
    echo   [ERROR] %FAIL_COUNT% file^(s^) failed to encrypt.
    echo           DO NOT proceed to cleanup.
    echo           Restore your backup and try again.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)

echo.
echo   [OK] Successfully encrypted %SUCCESS_COUNT% file^(s^).
echo.
echo   Press any key to verify encryption . . .
pause >nul

:: ============================================================
:: STEP 5 - Verify (sampled decryption)
:: ============================================================
echo.
echo [Step 5/7] Verifying encrypted assets . . .
echo.

if exist "%VERIFY_FILE%" del /q "%VERIFY_FILE%" 2>nul

node "encrypt_assets.js" --verify
if %errorlevel% neq 0 (
    echo.
    echo   [ERROR] Verification FAILED.
    echo           Encrypted files could not be decrypted correctly.
    echo           DO NOT proceed to cleanup.
    echo           Restore your backup and re-run this tool.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)

if not exist "%VERIFY_FILE%" (
    echo.
    echo   [ERROR] Verification did not produce a result file.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)

set "VERIFY_RESULT="
set /p VERIFY_RESULT=<"%VERIFY_FILE%"

echo.
echo   [OK] Verification passed: %VERIFY_RESULT%
echo.

:: ============================================================
:: STEP 6 - Cleanup confirmation
:: ============================================================
echo [Step 6/7] Sensitive file cleanup
echo.
echo   The following will be permanently DELETED:
echo     - All ORIGINAL asset files listed in the encryption log
echo       ^(plaintext images and audio^)
echo     - encrypt_config.json
echo       ^(contains the derivation seed^)
echo.
echo   This action CANNOT be undone.
echo   Make sure your source project is backed up elsewhere.
echo.
echo   Press any key to proceed . . .
pause >nul

:: ============================================================
:: STEP 7 - Delete sensitive files
:: ============================================================
echo.
echo [Step 7/7] Deleting sensitive files . . .
echo.

if not exist "%ORIGINALS_FILE%" (
    echo   [ERROR] Original file list not found.
    echo           Aborting deletion to prevent data loss.
    echo.
    echo   Press any key to exit . . .
    pause >nul
    exit /b 1
)

set "DELETED=0"

for /f "usebackq delims=" %%f in ("%ORIGINALS_FILE%") do (
    if exist "%%f" (
        del /q "%%f" 2>nul
        set /a DELETED+=1
    )
)

echo   [OK] Removed !DELETED! original asset file^(s^).

if exist "encrypt_config.json" (
    del /q "encrypt_config.json" 2>nul
    echo   [OK] encrypt_config.json removed.
)

if exist "%SCAN_FILE%"       del /q "%SCAN_FILE%"       2>nul
if exist "%RESULT_FILE%"     del /q "%RESULT_FILE%"     2>nul
if exist "%VERIFY_FILE%"     del /q "%VERIFY_FILE%"     2>nul
if exist "%ORIGINALS_FILE%"  del /q "%ORIGINALS_FILE%"  2>nul

echo.
echo ============================================================
echo   Encryption complete.
echo ============================================================
echo.
echo   Next steps ^(see documentation^):
echo     1. Verify decryptor.node is in the release package root.
echo     2. Verify that exactly ONE Chronos Seal wrapper plugin
echo        is present in js/plugins/.
echo     3. Verify index.html is the Chronos Seal version.
echo     4. Package and distribute.
echo.
echo   Reminder: delete this .bat file before distribution.
echo.
echo   Press any key to exit . . .
pause >nul

endlocal
exit /b 0